name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Branch que vai disparar o deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # ou a versão que você usa

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Build do Astro
      - name: Build Astro
        run: npm run build

      # 5. Deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist